apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.name" . }}-internal
  labels:
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.server.port }}
    name: server
  - port: {{ .Values.election.port }}
    name: leader-election
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.name" . }}
  labels:
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: client
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
